// Generated by CoffeeScript 1.3.3
var Circle, CircleInput, LETTER_CHECKING_DELAY, LETTER_CHECKING_TIME, Letter, LettersCtrl;

LETTER_CHECKING_TIME = 600;

LETTER_CHECKING_DELAY = 300;

CircleInput = $('#J_KeyBoardCircle');

Circle = CircleInput.knob({
  thickness: 0.3,
  width: 60
});

LettersCtrl = (function() {

  function LettersCtrl() {
    var letter, letters, _i, _len;
    this.letters = [];
    letters = [["Q", 23, 249], ["W", 99, 249], ["E", 175, 249], ["R", 252, 249], ["T", 330, 249], ["Y", 407, 249], ["U", 484, 249], ["I", 561, 249], ["O", 637, 249], ["P", 713, 249], ["A", 60, 328], ["S", 136, 328], ["D", 213, 328], ["F", 289, 328], ["G", 367, 328], ["H", 445, 328], ["J", 521, 328], ["K", 598, 328], ["L", 675, 328], ["Z", 97, 410], ["X", 173, 410], ["C", 250, 410], ["V", 326, 410], ["B", 404, 410], ["N", 481, 410], ["M", 558, 410], ["BackSpace", 531, 110], ["Enter", 655, 110]];
    for (_i = 0, _len = letters.length; _i < _len; _i++) {
      letter = letters[_i];
      this.letters.push(new Letter(letter[0], letter[1], letter[2]));
    }
    this.init();
  }

  LettersCtrl.prototype.init = function() {
    this.delayTimer = null;
    this.inputTimer = null;
    this.inLetter = "";
    return Circle.bind('change', function(ev) {
      if (ev.value >= 100) {
        return this.inputLetter(this.preLetter);
      }
    });
  };

  LettersCtrl.prototype.bind = function(x, y) {
    var letter,
      _this = this;
    this.x = x + 35;
    this.y = y + 35;
    letter = this.checkInLetter(x, y);
    Circle[0].style.cssText = "position: absolute; left: " + (this.x - 30) + "px; top: " + (this.y - 30) + "px;";
    if (letter === this.preLetter) {
      return;
    }
    clearTimeout(this.delayTimer);
    clearTimeout(this.inputTimer);
    this.hideProgress();
    if (!letter) {
      return;
    }
    this.preLetter = letter;
    return this.delayTimer = setTimeout(function() {
      return _this.checkAfterDelay.call(_this);
    }, LETTER_CHECKING_DELAY);
  };

  LettersCtrl.prototype.checkAfterDelay = function() {
    return this.showProgress();
  };

  LettersCtrl.prototype.inputLetter = function(letter) {
    var val;
    console.log(letter);
    if (!letter) {
      return;
    }
    val = $('#username').val();
    if (letter.letter === "BackSpace") {
      return $('#username').val(val.substring(0, val.length - 2));
    } else if (letter.letter === "Enter") {
      Watcher.clearTimer();
      return game.nextPhase(function() {
        game.on('start', function(mapArea) {
          return App.init(mapArea);
        });
        return Watcher.gameStart.bind(void 0, App.hit.bind(App))();
      });
    } else {
      val = $('#username').val();
      return $('#username').val(val + letter.letter);
    }
  };

  LettersCtrl.prototype.showProgress = function() {
    var value;
    Circle.show();
    CircleInput.val(6).trigger('change');
    clearInterval(this.progressTimer);
    value = 6;
    this.progressTimer = setInterval(function() {
      if (value >= 100) {
        return;
      }
      value = value + 6;
      return CircleInput.val(value).trigger('change');
    }, LETTER_CHECKING_TIME / 17);
  };

  LettersCtrl.prototype.hideProgress = function() {
    CircleInput.val(0).trigger('change');
    return clearInterval(this.progressTimer);
  };

  LettersCtrl.prototype.checkInLetter = function(x, y) {
    var letter, _i, _len, _ref;
    _ref = this.letters;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      letter = _ref[_i];
      if (letter.checkIsSelf(x, y)) {
        this.x = letter.x;
        this.y = letter.y;
        return letter;
        break;
      }
    }
    return false;
  };

  return LettersCtrl;

})();

Letter = (function() {

  Letter.prototype.width = 66;

  Letter.prototype.height = 66;

  function Letter(letter, x, y) {
    this.letter = letter;
    this.x = x;
    this.y = y;
    this.r = x + this.width;
    this.b = y + this.height;
  }

  Letter.prototype.checkIsSelf = function(x, y) {
    return x >= this.x && x <= this.r && y >= this.y && y <= this.b;
  };

  return Letter;

})();
