// Generated by CoffeeScript 1.3.3
var DING, HIT, SoundBox;

DING = new Audio;

DING.src = "../sound/013kt008.mp3";

HIT = new Audio;

HIT.src = "../sound/013kt096.mp3";

SoundBox = (function() {

  function SoundBox() {}

  SoundBox.play = function(type) {
    var audio;
    audio = window[type.toUpperCase()];
    audio.currentTime = 0;
    audio.pause();
    return audio.play();
  };

  return SoundBox;

})();
