// Generated by CoffeeScript 1.3.3
var console, onmessage;

console = {
  log: function(str) {
    return postMessage(str.toString());
  }
};

onmessage = function(ev) {
  var data;
  data = ev.data;
  return console.log(ev);
};
