// Generated by CoffeeScript 1.6.2
var beautify, fs, path;

path = require('path');

fs = require('fs');

beautify = require('js-beautify').js_beautify;

module.exports = (function() {
  var config;

  config = {};
  config.root_path = path.normalize(__dirname + '/..');
  config.records = JSON.parse(fs.readFileSync(__dirname + '/records.json', {
    encoding: 'utf-8'
  }));
  config.save_records = function() {
    return fs.writeFileSync(__dirname + '/records.json', beautify(JSON.stringify(config.records), {
      indent_size: 4
    }));
  };
  return config;
})();
